$(info Building HAL)

MODULE=hal
HAL_MODULE_PATH=.

# Target this makefile is building.
TARGET_TYPE = a
BUILD_PATH_EXT = $(HAL_BUILD_PATH_EXT)

DEPENDENCIES = platform rtxmath

include ../build/tlm.mk
