
MODULE=vision
WIRING_MODULE_PATH=.

# Target this makefile is building.
TARGET_TYPE = a
BUILD_PATH_EXT = $(BUILD_TARGET_PLATFORM)

DEPENDENCIES = platform hal geometry entities

include ../build/tlm.mk
