
MODULE=entities
ENTITIES_MODULE_PATH=.

# Target this makefile is building.
TARGET_TYPE = a
BUILD_PATH_EXT = $(BUILD_TARGET_PLATFORM)

DEPENDENCIES = platform geometry rtxmath vision

include ../build/tlm.mk
