MODULE=user
USER_MODULE_PATH=.

BUILD_PATH_EXT = $(USER_BUILD_PATH_EXT)

DEPENDENCIES = system vision geometry entities loc hal rtxmath platform

LIB_DEPS +=

include ../build/platform-id.mk

WARNINGS_AS_ERRORS ?= n

TARGET_TYPE = a

include ../build/tlm.mk
