RTXMATH_MODULE_NAME = rtxmath
RTXMATH_MODULE_PATH ?= $(PROJECT_ROOT)/$(RTXMATH_MODULE_NAME)
include $(call rwildcard,$(RTXMATH_MODULE_PATH)/,include.mk)

RTXMATH_BUILD_PATH_EXT = $(BUILD_TARGET_PLATFORM)
RTXMATH_LIB_DIR = $(BUILD_PATH_BASE)/$(RTXMATH_MODULE_NAME)/$(RTXMATH_BUILD_PATH_EXT)
RTXMATH_LIB_DEP = $(RTXMATH_LIB_DIR)/lib$(RTXMATH_MODULE_NAME).a
